import {
  SemesterTarget,
  AICTECategory,
  CertificateSubmission,
  UserProfile,
  AdminUser,
} from '../types';

export const SEMESTER_TARGETS: SemesterTarget[] = [
  {
    semester: 'SEM_1',
    semesterLabel: 'Sem I',
    academicYear: 'F.E. (First Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 48,
    cumulativeTargetPoints: 12,
  },
  {
    semester: 'SEM_2',
    semesterLabel: 'Sem II',
    academicYear: 'F.E. (First Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 100,
    cumulativeTargetPoints: 25,
  },
  {
    semester: 'SEM_3',
    semesterLabel: 'Sem III',
    academicYear: 'S.E. (Second Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 148,
    cumulativeTargetPoints: 37,
  },
  {
    semester: 'SEM_4',
    semesterLabel: 'Sem IV',
    academicYear: 'S.E. (Second Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 200,
    cumulativeTargetPoints: 50,
  },
  {
    semester: 'SEM_5',
    semesterLabel: 'Sem V',
    academicYear: 'T.E. (Third Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 248,
    cumulativeTargetPoints: 62,
  },
  {
    semester: 'SEM_6',
    semesterLabel: 'Sem VI',
    academicYear: 'T.E. (Third Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 300,
    cumulativeTargetPoints: 75,
  },
  {
    semester: 'SEM_7',
    semesterLabel: 'Sem VII',
    academicYear: 'B.E. (Fourth Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 348,
    cumulativeTargetPoints: 87,
  },
  {
    semester: 'SEM_8',
    semesterLabel: 'Sem VIII',
    academicYear: 'B.E. (Fourth Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 400,
    cumulativeTargetPoints: 100,
  },
];

export const AICTE_CATEGORIES: AICTECategory[] = [
  {
    id: 1,
    title: 'Literacy & Education Drive',
    shortCode: 'CAT-01',
    description: 'Helping local schools / underprivileged kids in achieving literacy & education.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 2,
    title: 'Sports & Physical Fitness Support',
    shortCode: 'CAT-02',
    description: 'Assisting schools or local communities in sports, yoga, and fitness initiatives.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 3,
    title: 'Rural Development & Swachh Bharat',
    shortCode: 'CAT-03',
    description: 'Village immersion, rural sanitation, Swachh Bharat Abhiyan & infrastructure aid.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 4,
    title: 'Disaster Relief & Healthcare Assistance',
    shortCode: 'CAT-04',
    description: 'Assisting local administration or hospitals in healthcare drives and disaster management.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 5,
    title: 'Environmental Protection & Energy Saving',
    shortCode: 'CAT-05',
    description: 'Tree plantation drives, e-waste collection, rainwater harvesting & green audits.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 6,
    title: 'Innovation, Hackathons & Competitions',
    shortCode: 'CAT-06',
    description: 'Participation in Smart India Hackathon, paper presentation, tech project competitions.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 25,
  },
  {
    id: 7,
    title: 'Blood Donation & Health Awareness',
    shortCode: 'CAT-07',
    description: 'Organizing or donating in blood camps, health screening drives, organ donation campaigns.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 8,
    title: 'NGO Volunteering & Community Care',
    shortCode: 'CAT-08',
    description: 'Volunteering with recognized NGOs, old age homes, differently-abled care facilities.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 9,
    title: 'Technical Event Organizing & Leadership',
    shortCode: 'CAT-09',
    description: 'Organizing national/state level symposiums, conferences, workshops & coding fests.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 10,
    title: 'NSS / NCC / Cultural Activity',
    shortCode: 'CAT-10',
    description: 'Active participation in NSS camps, NCC drills, state/national cultural events.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 11,
    title: 'Digital Literacy & Cyber Security Training',
    shortCode: 'CAT-11',
    description: 'Conducting cyber safety & e-governance awareness sessions for senior citizens & public.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 12,
    title: 'Skill Development & Entrepreneurship',
    shortCode: 'CAT-12',
    description: 'Vocational training sessions, entrepreneurship bootcamps & startup mentorship.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 13,
    title: 'Women Empowerment & Social Equity',
    shortCode: 'CAT-13',
    description: 'Awareness workshops on women safety, gender equality & self-defense training.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 14,
    title: 'Student Body & Club Leadership',
    shortCode: 'CAT-14',
    description: 'Serving as Class Representative, Student Council Officer, or Professional Body Lead.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 15,
    title: 'Industry Visits & Community Research',
    shortCode: 'CAT-15',
    description: 'Industrial study tours, applied community surveys & field research reports.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
];

export const DEFAULT_STUDENT: UserProfile = {
  id: 'STU-1032230434',
  name: 'Rahul Sharma',
  email: '1032230434@tcetmumbai.in',
  role: 'student',
  rollNo: '1',
  erpNo: '2023011245',
  department: 'Internet of Things (IoT)',
  division: 'A',
  academicBatch: '2023-2027',
  driveRootFolderId: 'drive_folder_rahul_sharma_2023',
};

export const STUDENT_VIKRAM: UserProfile = {
  id: 'STU-2024011018',
  name: 'Vikramaditya Joshi',
  email: '2024011018@tcetmumbai.in',
  role: 'student',
  rollNo: '2',
  erpNo: '2024011018',
  department: 'Internet of Things (IoT)',
  division: 'B',
  academicBatch: '2024-2028',
  driveRootFolderId: 'drive_folder_vikram_joshi_2024',
};

export const STUDENT_SNEHA: UserProfile = {
  id: 'STU-2023012129',
  name: 'Sneha Kulkarni',
  email: '2023012129@tcetmumbai.in',
  role: 'student',
  rollNo: '3',
  erpNo: '2023012129',
  department: 'Internet of Things (IoT)',
  division: 'A',
  academicBatch: '2023-2027',
  driveRootFolderId: 'drive_folder_sneha_kulkarni_2023',
};

export const STUDENT_AARAV: UserProfile = {
  id: 'STU-2022013003',
  name: 'Aarav Deshmukh',
  email: '2022013003@tcetmumbai.in',
  role: 'student',
  rollNo: '4',
  erpNo: '2022013003',
  department: 'Internet of Things (IoT)',
  division: 'A',
  academicBatch: '2022-2026',
  driveRootFolderId: 'drive_folder_aarav_deshmukh_2022',
};

// ---- CR Accounts: CSE (IoT) Division A ----
export const CR_A1: UserProfile = {
  id: 'CR-IOT-A1',
  name: 'Riya Sharma (CR A1)',
  email: 'cr.iot.a1@tcetmumbai.in',
  password: 'CrA1@tcet2026!',
  role: 'cr',
  rollNo: 'CR-A1',
  erpNo: 'ERP-CR-A1',
  department: 'Internet of Things (IoT)',
  division: 'A',
  academicBatch: '2023-2027',
  tgmApprovalStatus: 'approved',
  crName: 'Riya Sharma (CR A1)',
};

export const CR_A2: UserProfile = {
  id: 'CR-IOT-A2',
  name: 'Arjun Desai (CR A2)',
  email: 'cr.iot.a2@tcetmumbai.in',
  password: 'CrA2@tcet2026!',
  role: 'cr',
  rollNo: 'CR-A2',
  erpNo: 'ERP-CR-A2',
  department: 'Internet of Things (IoT)',
  division: 'A',
  academicBatch: '2023-2027',
  tgmApprovalStatus: 'approved',
  crName: 'Arjun Desai (CR A2)',
};

// ---- CR Accounts: CSE (IoT) Division B ----
export const CR_B1: UserProfile = {
  id: 'CR-IOT-B1',
  name: 'Meera Patil (CR B1)',
  email: 'cr.iot.b1@tcetmumbai.in',
  password: 'CrB1@tcet2026!',
  role: 'cr',
  rollNo: 'CR-B1',
  erpNo: 'ERP-CR-B1',
  department: 'Internet of Things (IoT)',
  division: 'B',
  academicBatch: '2023-2027',
  tgmApprovalStatus: 'approved',
  crName: 'Meera Patil (CR B1)',
};

export const CR_B2: UserProfile = {
  id: 'CR-IOT-B2',
  name: 'Sahil Joshi (CR B2)',
  email: 'cr.iot.b2@tcetmumbai.in',
  password: 'CrB2@tcet2026!',
  role: 'cr',
  rollNo: 'CR-B2',
  erpNo: 'ERP-CR-B2',
  department: 'Internet of Things (IoT)',
  division: 'B',
  academicBatch: '2023-2027',
  tgmApprovalStatus: 'approved',
  crName: 'Sahil Joshi (CR B2)',
};

// ---- CR Accounts: CSE (IoT) 2024-2028 (No Division) ----
export const CR_2024_1: UserProfile = {
  id: 'CR-IOT-24-1',
  name: 'Aditya Kumar (CR 24-28)',
  email: 'cr.iot.2024.1@tcetmumbai.in',
  password: 'Cr24@tcet2028!',
  role: 'cr',
  rollNo: 'CR-24-1',
  erpNo: 'ERP-CR-24-1',
  department: 'Internet of Things (IoT)',
  division: 'N/A',
  academicBatch: '2024-2028',
  tgmApprovalStatus: 'approved',
  crName: 'Aditya Kumar (CR 24-28)',
};

export const CR_2024_2: UserProfile = {
  id: 'CR-IOT-24-2',
  name: 'Priya Sharma (CR 24-28)',
  email: 'cr.iot.2024.2@tcetmumbai.in',
  password: 'Cr24@tcet2028!',
  role: 'cr',
  rollNo: 'CR-24-2',
  erpNo: 'ERP-CR-24-2',
  department: 'Internet of Things (IoT)',
  division: 'N/A',
  academicBatch: '2024-2028',
  tgmApprovalStatus: 'approved',
  crName: 'Priya Sharma (CR 24-28)',
};


export const DEMO_STUDENT_PROFILES: { profile: UserProfile; levelTitle: string; ptsLabel: string; badgeColor: string }[] = [
  {
    profile: DEFAULT_STUDENT,
    levelTitle: 'Intermediate Level (27 Points)',
    ptsLabel: '27 / 100 Pts (SE)',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  },
  {
    profile: STUDENT_VIKRAM,
    levelTitle: 'Beginner Level (14 Points)',
    ptsLabel: '14 / 100 Pts (FE)',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
  },
  {
    profile: STUDENT_SNEHA,
    levelTitle: 'On-Track SE Target (50 Points)',
    ptsLabel: '50 / 100 Pts (SE)',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  },
  {
    profile: STUDENT_AARAV,
    levelTitle: 'High Achiever (88 Points)',
    ptsLabel: '88 / 100 Pts (BE)',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
  },
];

export const SUPERADMIN_PROFILE: UserProfile = {
  id: 'SUPERADMIN-001',
  name: 'Dr. B. K. Mishra (Principal & Super Admin)',
  email: 'superadmin@tcetmumbai.in',
  role: 'superadmin',
  rollNo: 'SA-01',
  erpNo: 'ERP-SUPER-001',
  department: 'Institutional Head Office',
  division: 'All Departments',
  academicBatch: 'Principal / Head',
  tgmApprovalStatus: 'approved',
};

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: 'ADM-SUPER',
    email: 'superadmin@tcetmumbai.in',
    name: 'Dr. B. K. Mishra (Principal)',
    designation: 'Principal & Chief Super Admin',
    department: 'Institutional Head Office',
    addedBy: 'TCET Governing Council',
    addedAt: '2024-01-01',
    isWhitelisted: true,
    approvalStatus: 'approved',
  },
  {
    id: 'ADM-1',
    email: '1032230434@tcetmumbai.in',
    name: 'Rahul Sharma (Admin Mode)',
    designation: 'Teacher Guardian Mentor (TGM)',
    department: 'Internet of Things (IoT)',
    addedBy: 'System Auto-provision',
    addedAt: '2026-01-15',
    isWhitelisted: true,
    approvalStatus: 'approved',
  },
  {
    id: 'ADM-2',
    email: 'skmehta@tcetmumbai.in',
    name: 'Prof. S. K. Mehta',
    designation: 'Senior TGM & Assistant Professor',
    department: 'Internet of Things (IoT)',
    addedBy: 'HOD IoT',
    addedAt: '2025-08-10',
    isWhitelisted: true,
    approvalStatus: 'approved',
  },
  {
    id: 'ADM-3',
    email: 'aicte_coordinator@tcetmumbai.in',
    name: 'Dr. Rajesh Patel',
    designation: 'TCET AICTE Activity Head',
    department: 'Internet of Things (IoT)',
    addedBy: 'Principal Office',
    addedAt: '2024-07-01',
    isWhitelisted: true,
    approvalStatus: 'approved',
  },
];

export const INITIAL_SUBMISSIONS: CertificateSubmission[] = [
  {
    id: 'SUB-101',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Swachh Bharat Cleanliness Drive & Tree Plantation',
    conductedBy: 'TCET NSS Unit & Local Panchayat',
    activityCategoryNo: 3,
    shortDescription: 'Participated in 3-day sanitation awareness and planted 15 saplings in adopted village.',
    hoursSpent: 24,
    calculatedPoints: 6,
    currentFileDriveId: 'DRIVE_FILE_SEM1_01_v2',
    fileName: 'Swachh_Bharat_Cert_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM1_01_v1', 'DRIVE_FILE_SEM1_01_v2'],
    isCheckedByCR: true,
    crCheckedAt: '2023-11-10T10:30:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-11-14T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    tgmRemarks: 'Verified certificate against NSS register. Excellent effort.',
    status: 'approved',
    createdAt: '2023-11-05T09:00:00Z',
    updatedAt: '2023-11-14T15:00:00Z',
  },
  {
    id: 'SUB-102',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Primary School Science & Digital Literacy Workshop',
    conductedBy: 'Rotaract Club of TCET',
    activityCategoryNo: 1,
    shortDescription: 'Taught basic computer usage and science experiments to 4th grade students.',
    hoursSpent: 24,
    calculatedPoints: 6,
    currentFileDriveId: 'DRIVE_FILE_SEM1_02_v1',
    fileName: 'Digital_Literacy_Cert_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM1_02_v1'],
    isCheckedByCR: true,
    crCheckedAt: '2023-12-01T11:20:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-12-05T14:10:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    tgmRemarks: 'Duly signed by Rotaract Coordinator.',
    status: 'approved',
    createdAt: '2023-11-28T14:00:00Z',
    updatedAt: '2023-12-05T14:10:00Z',
  },
  {
    id: 'SUB-201',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'National Blood Donation Drive Volunteer',
    conductedBy: 'TCET Medical Committee & KEM Hospital',
    activityCategoryNo: 7,
    shortDescription: 'Assisted in organizing donor registration and refreshments for 450+ donors.',
    hoursSpent: 20,
    calculatedPoints: 5,
    currentFileDriveId: 'DRIVE_FILE_SEM2_01_v1',
    fileName: 'Blood_Donation_Vol_Cert_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM2_01_v1'],
    isCheckedByCR: true,
    crCheckedAt: '2024-03-12T09:45:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-03-18T16:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    tgmRemarks: 'Verified with TCET Medical Cell.',
    status: 'approved',
    createdAt: '2024-03-10T12:00:00Z',
    updatedAt: '2024-03-18T16:00:00Z',
  },
  {
    id: 'SUB-202',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'ZEAL National Cultural Fest Event Manager',
    conductedBy: 'TCET Student Council',
    activityCategoryNo: 9,
    shortDescription: 'Coordinated logistics and stage management for national inter-college competition.',
    hoursSpent: 32,
    calculatedPoints: 8,
    currentFileDriveId: 'DRIVE_FILE_SEM2_02_v1',
    fileName: 'Zeal_Fest_Coordinator_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM2_02_v1'],
    isCheckedByCR: true,
    crCheckedAt: '2024-04-10T14:15:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-04-15T11:30:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-04-15T11:30:00Z',
  },
  {
    id: 'SUB-301',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'Smart India Hackathon College Level Winner',
    conductedBy: 'MoE Innovation Cell & TCET IIC',
    activityCategoryNo: 6,
    shortDescription: 'Developed IoT prototype for Smart Agriculture and won 1st position in institute round.',
    hoursSpent: 28,
    calculatedPoints: 7,
    currentFileDriveId: 'DRIVE_FILE_SEM3_01_v1',
    fileName: 'SIH_Internal_Winner_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM3_01_v1'],
    isCheckedByCR: true,
    crCheckedAt: '2024-09-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-09-25T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-09-18T16:00:00Z',
    updatedAt: '2024-09-25T14:00:00Z',
  },
  {
    id: 'SUB-302',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'Cyber Safety & Anti-Phishing Drive for Seniors',
    conductedBy: 'TCET ACM Student Chapter',
    activityCategoryNo: 11,
    shortDescription: 'Helped 35 senior citizens set up 2FA and learn safe UPI payment practices.',
    hoursSpent: 20,
    calculatedPoints: 5,
    currentFileDriveId: 'DRIVE_FILE_SEM3_02_v1',
    fileName: 'Cyber_Safety_Workshop_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM3_02_v1'],
    isCheckedByCR: true,
    crCheckedAt: '2024-10-15T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: false,
    status: 'pending_admin',
    createdAt: '2024-10-10T10:00:00Z',
    updatedAt: '2024-10-15T12:00:00Z',
  },
  {
    id: 'SUB-401',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_4',
    activityName: 'E-Waste Awareness & Collection Drive',
    conductedBy: 'TCET Green Club & EcoRecycle Ltd',
    activityCategoryNo: 5,
    shortDescription: 'Collected 120kg of electronic waste from Kandivali area and handed to certified recyclers.',
    hoursSpent: 24,
    calculatedPoints: 6,
    currentFileDriveId: 'DRIVE_FILE_SEM4_01_v1',
    fileName: 'EWaste_Collection_SEM4.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM4_01_v1'],
    isCheckedByCR: false,
    isVerifiedByTGM: false,
    status: 'pending_cr',
    createdAt: '2025-02-14T08:30:00Z',
    updatedAt: '2025-02-14T08:30:00Z',
  },
  {
    id: 'SUB-402',
    studentId: 'STU-1032230434',
    studentName: 'Rahul Sharma',
    studentRollNo: '1',
    studentErpNo: '2023011245',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_4',
    activityName: 'IEEE State Level Paper Presentation on AI in Healthcare',
    conductedBy: 'IEEE Bombay Section',
    activityCategoryNo: 6,
    shortDescription: 'Presented research paper on AI medical diagnosis algorithms.',
    hoursSpent: 28,
    calculatedPoints: 7,
    currentFileDriveId: 'DRIVE_FILE_SEM4_02_v2',
    fileName: 'IEEE_Paper_Cert_SEM4_v2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SEM4_02_v1', 'DRIVE_FILE_SEM4_02_v2'],
    isCheckedByCR: true,
    crCheckedAt: '2025-03-01T14:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    crRemarks: 'Updated certificate with stamp reuploaded as requested.',
    isVerifiedByTGM: false,
    status: 'pending_admin',
    createdAt: '2025-02-20T11:00:00Z',
    updatedAt: '2025-03-01T14:00:00Z',
  },
  {
    id: 'SUB-403',
    studentId: 'STU-1032230434',
    studentName: 'Priya Singh',
    studentRollNo: '5',
    studentErpNo: '2023011988',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_4',
    activityName: 'Women in Tech Mentorship Workshop',
    conductedBy: 'TCET WIE Chapter',
    activityCategoryNo: 13,
    shortDescription: 'Organized self-defense and tech career workshops for junior female students.',
    hoursSpent: 20,
    calculatedPoints: 5,
    currentFileDriveId: 'DRIVE_FILE_PRIYA_SEM4_01',
    fileName: 'Priya_WomenInTech_SEM4.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_PRIYA_SEM4_01'],
    isCheckedByCR: false,
    isVerifiedByTGM: false,
    status: 'pending_cr',
    createdAt: '2025-03-10T16:00:00Z',
    updatedAt: '2025-03-10T16:00:00Z',
  },
  {
    id: 'SUB-PRI-101',
    studentId: 'STU-2023011988',
    studentName: 'Priya Singh',
    studentRollNo: '5',
    studentErpNo: '2023011988',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Rural Health & Sanitation Campaign',
    conductedBy: 'TCET NSS Unit',
    activityCategoryNo: 3,
    shortDescription: 'Organized village cleanliness and hygiene awareness workshops.',
    hoursSpent: 40,
    calculatedPoints: 10,
    currentFileDriveId: 'DRIVE_FILE_PRIYA_SEM1_01',
    fileName: 'Priya_HealthCampaign_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_PRIYA_SEM1_01'],
    isCheckedByCR: true,
    crCheckedAt: '2023-11-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-11-28T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2023-11-15T09:00:00Z',
    updatedAt: '2023-11-28T15:00:00Z',
  },
  {
    id: 'SUB-PRI-201',
    studentId: 'STU-2023011988',
    studentName: 'Priya Singh',
    studentRollNo: '5',
    studentErpNo: '2023011988',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'Tree Plantation & Environmental Conservation',
    conductedBy: 'Rotaract Club of TCET',
    activityCategoryNo: 5,
    shortDescription: 'Planted 15 saplings and maintained botanical nursery on campus.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_PRIYA_SEM2_01',
    fileName: 'Priya_TreePlantation_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_PRIYA_SEM2_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-04-10T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-04-18T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-04-18T14:00:00Z',
  },
  {
    id: 'SUB-PRI-301',
    studentId: 'STU-2023011988',
    studentName: 'Priya Singh',
    studentRollNo: '5',
    studentErpNo: '2023011988',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'National Coding Competition Lead Volunteer',
    conductedBy: 'TCET ACM Student Chapter',
    activityCategoryNo: 9,
    shortDescription: 'Coordinated logistics and student registrations for 300+ participants.',
    hoursSpent: 40,
    calculatedPoints: 10,
    currentFileDriveId: 'DRIVE_FILE_PRIYA_SEM3_01',
    fileName: 'Priya_ACM_Volunteer_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_PRIYA_SEM3_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-10-12T09:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-10-20T11:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-10-08T14:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
  },

  // AMIT PATEL
  {
    id: 'SUB-AMI-101',
    studentId: 'STU-2023012001',
    studentName: 'Amit Patel',
    studentRollNo: '6',
    studentErpNo: '2023012001',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Disaster Relief & Community Food Distribution',
    conductedBy: 'TCET Social Welfare Cell',
    activityCategoryNo: 8,
    shortDescription: 'Distributed ration packets and essential supplies during monsoon flood relief.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_AMIT_SEM1_01',
    fileName: 'Amit_DisasterRelief_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AMIT_SEM1_01'],
    isCheckedByCR: true,
    crCheckedAt: '2023-11-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-11-28T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2023-11-15T09:00:00Z',
    updatedAt: '2023-11-28T15:00:00Z',
  },
  {
    id: 'SUB-AMI-201',
    studentId: 'STU-2023012001',
    studentName: 'Amit Patel',
    studentRollNo: '6',
    studentErpNo: '2023012001',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'Energy Audit & Power Saving Awareness Campaign',
    conductedBy: 'TCET Electrical Dept & Green Cell',
    activityCategoryNo: 5,
    shortDescription: 'Audited campus electricity usage and conducted energy saving workshops.',
    hoursSpent: 60,
    calculatedPoints: 15,
    currentFileDriveId: 'DRIVE_FILE_AMIT_SEM2_01',
    fileName: 'Amit_EnergyAudit_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AMIT_SEM2_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-04-10T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-04-18T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-04-18T14:00:00Z',
  },
  {
    id: 'SUB-AMI-301',
    studentId: 'STU-2023012001',
    studentName: 'Amit Patel',
    studentRollNo: '6',
    studentErpNo: '2023012001',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'Open Source Software Development BootCamp',
    conductedBy: 'TCET OpenSource Club',
    activityCategoryNo: 6,
    shortDescription: 'Contributed 3 bug fixes and documentation to open-source college repository.',
    hoursSpent: 56,
    calculatedPoints: 14,
    currentFileDriveId: 'DRIVE_FILE_AMIT_SEM3_01',
    fileName: 'Amit_OpenSource_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AMIT_SEM3_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-10-12T09:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-10-20T11:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-10-08T14:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
  },

  // ==========================================
  // VIKRAMADITYA JOSHI (Beginner FE - 14 Points)
  // ==========================================
  {
    id: 'SUB-VIK-101',
    studentId: 'STU-2024011018',
    studentName: 'Vikramaditya Joshi',
    studentRollNo: '2',
    studentErpNo: '2024011018',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'B',
    semester: 'SEM_1',
    activityName: 'Swachh Bharat Cleanliness & Tree Plantation Campaign',
    conductedBy: 'TCET NSS Unit & Local Gram Panchayat',
    activityCategoryNo: 3,
    shortDescription: 'Participated in a 4-day sanitation campaign and planted 12 trees near Kandivali forest area.',
    hoursSpent: 32,
    calculatedPoints: 8,
    currentFileDriveId: 'DRIVE_FILE_VIKRAM_SEM1_01',
    fileName: 'Vikram_SwachhBharat_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_VIKRAM_SEM1_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-11-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-11-25T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2024-11-25T14:00:00Z',
  },
  {
    id: 'SUB-VIK-201',
    studentId: 'STU-2024011018',
    studentName: 'Vikramaditya Joshi',
    studentRollNo: '2',
    studentErpNo: '2024011018',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'B',
    semester: 'SEM_2',
    activityName: 'Disaster Management & First Aid Training Workshop',
    conductedBy: 'Red Cross Society & TCET Safety Cell',
    activityCategoryNo: 8,
    shortDescription: 'Completed 24-hour certified first-aid and fire rescue simulation training.',
    hoursSpent: 24,
    calculatedPoints: 6,
    currentFileDriveId: 'DRIVE_FILE_VIKRAM_SEM2_01',
    fileName: 'Vikram_RedCross_FirstAid_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_VIKRAM_SEM2_01'],
    isCheckedByCR: true,
    crCheckedAt: '2025-04-05T11:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2025-04-10T16:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2025-04-01T08:00:00Z',
    updatedAt: '2025-04-10T16:00:00Z',
  },
  {
    id: 'SUB-VIK-202',
    studentId: 'STU-2024011018',
    studentName: 'Vikramaditya Joshi',
    studentRollNo: '2',
    studentErpNo: '2024011018',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'B',
    semester: 'SEM_2',
    activityName: 'Village Primary School Digital Literacy Camp',
    conductedBy: 'Rotaract Club of TCET',
    activityCategoryNo: 1,
    shortDescription: 'Taught basic laptop operation and internet safety to 25 primary school kids.',
    hoursSpent: 20,
    calculatedPoints: 5,
    currentFileDriveId: 'DRIVE_FILE_VIKRAM_SEM2_02',
    fileName: 'Vikram_DigitalLiteracy_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_VIKRAM_SEM2_02'],
    isCheckedByCR: false,
    isVerifiedByTGM: false,
    status: 'pending_cr',
    createdAt: '2025-05-02T10:00:00Z',
    updatedAt: '2025-05-02T10:00:00Z',
  },

  // ==========================================
  // SNEHA KULKARNI (On-Track SE - 50 Points)
  // ==========================================
  {
    id: 'SUB-SNE-101',
    studentId: 'STU-2023012129',
    studentName: 'Sneha Kulkarni',
    studentRollNo: '3',
    studentErpNo: '2023012129',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Rural Primary School Teaching & STEM Kit Distribution',
    conductedBy: 'TCET NSS & Pratham NGO',
    activityCategoryNo: 1,
    shortDescription: 'Distributed 100+ educational kits and taught basic science concepts for 48 hours.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_SNEHA_SEM1_01',
    fileName: 'Sneha_STEM_Teaching_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SNEHA_SEM1_01'],
    isCheckedByCR: true,
    crCheckedAt: '2023-11-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-11-28T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2023-11-15T09:00:00Z',
    updatedAt: '2023-11-28T15:00:00Z',
  },
  {
    id: 'SUB-SNE-201',
    studentId: 'STU-2023012129',
    studentName: 'Sneha Kulkarni',
    studentRollNo: '3',
    studentErpNo: '2023012129',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'Blood Donation & General Health Checkup Drive Lead',
    conductedBy: 'TCET Medical Committee',
    activityCategoryNo: 7,
    shortDescription: 'Managed registrations and donor triage for annual campus blood donation drive.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_SNEHA_SEM2_01',
    fileName: 'Sneha_BloodDonation_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SNEHA_SEM2_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-04-10T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-04-18T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-04-18T14:00:00Z',
  },
  {
    id: 'SUB-SNE-301',
    studentId: 'STU-2023012129',
    studentName: 'Sneha Kulkarni',
    studentRollNo: '3',
    studentErpNo: '2023012129',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'TCET Technical Fest Robotics Workshop Coordinator',
    conductedBy: 'IETE TCET Student Forum',
    activityCategoryNo: 9,
    shortDescription: 'Coordinated a 3-day line-follower robotics hands-on training for 120 participants.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_SNEHA_SEM3_01',
    fileName: 'Sneha_RoboticsWorkshop_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SNEHA_SEM3_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-10-12T09:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-10-20T11:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-10-08T14:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
  },
  {
    id: 'SUB-SNE-401',
    studentId: 'STU-2023012129',
    studentName: 'Sneha Kulkarni',
    studentRollNo: '3',
    studentErpNo: '2023012129',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_4',
    activityName: 'E-Waste Recycling & Plastic Segregation Campaign',
    conductedBy: 'TCET Green Club & Municipal Corporation',
    activityCategoryNo: 5,
    shortDescription: 'Led door-to-door e-waste drive collecting 200+ broken electronics and old batteries.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_SNEHA_SEM4_01',
    fileName: 'Sneha_EWaste_Recycling_SEM4.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_SNEHA_SEM4_01'],
    isCheckedByCR: true,
    crCheckedAt: '2025-03-15T14:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2025-03-22T10:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2025-03-10T11:00:00Z',
    updatedAt: '2025-03-22T10:00:00Z',
  },

  // ==========================================
  // AARAV DESHMUKH (High Achiever BE - 88 Points)
  // ==========================================
  {
    id: 'SUB-AAR-101',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_1',
    activityName: 'Slum Children Literacy & Arithmetic Foundation',
    conductedBy: 'Rotaract Club of TCET',
    activityCategoryNo: 1,
    shortDescription: 'Taught basic mathematics and reading skills for 48 hours in Malad East slum cluster.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM1_01',
    fileName: 'Aarav_Slum_Literacy_SEM1.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM1_01'],
    isCheckedByCR: true,
    crCheckedAt: '2022-11-20T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2022-11-28T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2022-11-15T09:00:00Z',
    updatedAt: '2022-11-28T15:00:00Z',
  },
  {
    id: 'SUB-AAR-201',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_2',
    activityName: 'NSS National Integration Camp Student Representative',
    conductedBy: 'Ministry of Youth Affairs & Sports & TCET NSS',
    activityCategoryNo: 4,
    shortDescription: 'Represented institute in 7-day residential camp focusing on national unity and village adoption.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM2_01',
    fileName: 'Aarav_NSS_NationalCamp_SEM2.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM2_01'],
    isCheckedByCR: true,
    crCheckedAt: '2023-04-10T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-04-18T14:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2023-04-05T10:00:00Z',
    updatedAt: '2023-04-18T14:00:00Z',
  },
  {
    id: 'SUB-AAR-301',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_3',
    activityName: 'IEEE International Conference Research Paper Lead',
    conductedBy: 'IEEE Bombay Section',
    activityCategoryNo: 6,
    shortDescription: 'Published and presented research paper on ML algorithms for social welfare routing.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM3_01',
    fileName: 'Aarav_IEEE_Paper_SEM3.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM3_01'],
    isCheckedByCR: true,
    crCheckedAt: '2023-10-12T09:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2023-10-20T11:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2023-10-08T14:00:00Z',
    updatedAt: '2023-10-20T11:00:00Z',
  },
  {
    id: 'SUB-AAR-401',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_4',
    activityName: 'Rural Solar Electrification & Energy Survey',
    conductedBy: 'TCET Green Energy Cell & Tata Power CSR',
    activityCategoryNo: 5,
    shortDescription: 'Installed 10 solar lanterns in tribal hamlets of Palghar district.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM4_01',
    fileName: 'Aarav_SolarElectrification_SEM4.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM4_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-03-15T14:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-03-22T10:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-22T10:00:00Z',
  },
  {
    id: 'SUB-AAR-501',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_5',
    activityName: 'Smart City Traffic Safety & Helmet Awareness Campaign',
    conductedBy: 'Mumbai Traffic Police & TCET NSS',
    activityCategoryNo: 11,
    shortDescription: 'Organized street plays and road safety drives at Western Express Highway junctions.',
    hoursSpent: 48,
    calculatedPoints: 12,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM5_01',
    fileName: 'Aarav_TrafficSafety_SEM5.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM5_01'],
    isCheckedByCR: true,
    crCheckedAt: '2024-11-05T10:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2024-11-12T16:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-11-12T16:00:00Z',
  },
  {
    id: 'SUB-AAR-601',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_6',
    activityName: 'Rotaract Club Vice President Community Leadership',
    conductedBy: 'Rotaract District 3141',
    activityCategoryNo: 14,
    shortDescription: 'Served as Vice President leading 15+ social impact projects affecting 2,000+ citizens.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM6_01',
    fileName: 'Aarav_RotaractVP_Leadership_SEM6.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM6_01'],
    isCheckedByCR: true,
    crCheckedAt: '2025-04-10T11:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2025-04-18T15:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2025-04-05T09:00:00Z',
    updatedAt: '2025-04-18T15:00:00Z',
  },
  {
    id: 'SUB-AAR-701',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_7',
    activityName: 'AI for Social Good - Assistive Speech Tech for Visually Impaired',
    conductedBy: 'TCET Research & Innovation Cell',
    activityCategoryNo: 6,
    shortDescription: 'Built open-source voice navigation assistant and deployed at Blind Relief Association.',
    hoursSpent: 52,
    calculatedPoints: 13,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM7_01',
    fileName: 'Aarav_AI_AssistiveTech_SEM7.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM7_01'],
    isCheckedByCR: true,
    crCheckedAt: '2025-11-10T12:00:00Z',
    crCheckedBy: 'Riya Sharma (CR A1)',
    isVerifiedByTGM: true,
    tgmVerifiedAt: '2025-11-18T10:00:00Z',
    tgmVerifiedBy: 'Prof. S. K. Mehta',
    status: 'approved',
    createdAt: '2025-11-05T14:00:00Z',
    updatedAt: '2025-11-18T10:00:00Z',
  },
  {
    id: 'SUB-AAR-801',
    studentId: 'STU-2022013003',
    studentName: 'Aarav Deshmukh',
    studentRollNo: '4',
    studentErpNo: '2022013003',
    studentDepartment: 'Internet of Things (IoT)',
    studentDivision: 'A',
    semester: 'SEM_8',
    activityName: 'National Cyber Security Awareness & Scam Protection Campaign',
    conductedBy: 'Cyber Peace Foundation & TCET ACM',
    activityCategoryNo: 11,
    shortDescription: 'Conducted 10 interactive cyber security workshops for high school students.',
    hoursSpent: 40,
    calculatedPoints: 10,
    currentFileDriveId: 'DRIVE_FILE_AARAV_SEM8_01',
    fileName: 'Aarav_CyberSecurity_SEM8.pdf',
    fileDriveIdHistory: ['DRIVE_FILE_AARAV_SEM8_01'],
    isCheckedByCR: false,
    isVerifiedByTGM: false,
    status: 'pending_cr',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-10T09:00:00Z',
  },
];
