import {
  SemesterTarget,
  AICTECategory,
} from '../types';

export const SEMESTER_TARGETS: SemesterTarget[] = [
  {
    semester: 'SEM_1',
    semesterLabel: 'Sem I',
    academicYear: 'F.E. (First Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 48,
    cumulativeTargetPoints: 12,
  },
  {
    semester: 'SEM_2',
    semesterLabel: 'Sem II',
    academicYear: 'F.E. (First Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 100,
    cumulativeTargetPoints: 25,
  },
  {
    semester: 'SEM_3',
    semesterLabel: 'Sem III',
    academicYear: 'S.E. (Second Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 148,
    cumulativeTargetPoints: 37,
  },
  {
    semester: 'SEM_4',
    semesterLabel: 'Sem IV',
    academicYear: 'S.E. (Second Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 200,
    cumulativeTargetPoints: 50,
  },
  {
    semester: 'SEM_5',
    semesterLabel: 'Sem V',
    academicYear: 'T.E. (Third Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 248,
    cumulativeTargetPoints: 62,
  },
  {
    semester: 'SEM_6',
    semesterLabel: 'Sem VI',
    academicYear: 'T.E. (Third Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 300,
    cumulativeTargetPoints: 75,
  },
  {
    semester: 'SEM_7',
    semesterLabel: 'Sem VII',
    academicYear: 'B.E. (Fourth Year)',
    isOdd: true,
    targetHours: 48,
    targetPoints: 12,
    cumulativeTargetHours: 348,
    cumulativeTargetPoints: 87,
  },
  {
    semester: 'SEM_8',
    semesterLabel: 'Sem VIII',
    academicYear: 'B.E. (Fourth Year)',
    isOdd: false,
    targetHours: 52,
    targetPoints: 13,
    cumulativeTargetHours: 400,
    cumulativeTargetPoints: 100,
  },
];
export const AICTE_CATEGORIES: AICTECategory[] = [
  {
    id: 1,
    title: 'Literacy & Education Drive',
    shortCode: 'CAT-01',
    description: 'Helping local schools / underprivileged kids in achieving literacy & education.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 2,
    title: 'Sports & Physical Fitness Support',
    shortCode: 'CAT-02',
    description: 'Assisting schools or local communities in sports, yoga, and fitness initiatives.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 3,
    title: 'Rural Development & Swachh Bharat',
    shortCode: 'CAT-03',
    description: 'Village immersion, rural sanitation, Swachh Bharat Abhiyan & infrastructure aid.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 4,
    title: 'Disaster Relief & Healthcare Assistance',
    shortCode: 'CAT-04',
    description: 'Assisting local administration or hospitals in healthcare drives and disaster management.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 5,
    title: 'Environmental Protection & Energy Saving',
    shortCode: 'CAT-05',
    description: 'Tree plantation drives, e-waste collection, rainwater harvesting & green audits.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 6,
    title: 'Innovation, Hackathons & Competitions',
    shortCode: 'CAT-06',
    description: 'Participation in Smart India Hackathon, paper presentation, tech project competitions.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 25,
  },
  {
    id: 7,
    title: 'Blood Donation & Health Awareness',
    shortCode: 'CAT-07',
    description: 'Organizing or donating in blood camps, health screening drives, organ donation campaigns.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 8,
    title: 'NGO Volunteering & Community Care',
    shortCode: 'CAT-08',
    description: 'Volunteering with recognized NGOs, old age homes, differently-abled care facilities.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 9,
    title: 'Technical Event Organizing & Leadership',
    shortCode: 'CAT-09',
    description: 'Organizing national/state level symposiums, conferences, workshops & coding fests.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 10,
    title: 'NSS / NCC / Cultural Activity',
    shortCode: 'CAT-10',
    description: 'Active participation in NSS camps, NCC drills, state/national cultural events.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 11,
    title: 'Digital Literacy & Cyber Security Training',
    shortCode: 'CAT-11',
    description: 'Conducting cyber safety & e-governance awareness sessions for senior citizens & public.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 12,
    title: 'Skill Development & Entrepreneurship',
    shortCode: 'CAT-12',
    description: 'Vocational training sessions, entrepreneurship bootcamps & startup mentorship.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 20,
  },
  {
    id: 13,
    title: 'Women Empowerment & Social Equity',
    shortCode: 'CAT-13',
    description: 'Awareness workshops on women safety, gender equality & self-defense training.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 14,
    title: 'Student Body & Club Leadership',
    shortCode: 'CAT-14',
    description: 'Serving as Class Representative, Student Council Officer, or Professional Body Lead.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 15,
    title: 'Industry Visits & Community Research',
    shortCode: 'CAT-15',
    description: 'Industrial study tours, applied community surveys & field research reports.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
  {
    id: 16,
    title: 'Other Approved Activity',
    shortCode: 'CAT-16',
    description: 'Other institution-approved activities eligible for AICTE activity points.',
    minHoursPerPoint: 4,
    maxPointsAllowed: 15,
  },
];
