import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
export function TeacherProfile({ userId, readOnly = false }: { userId: string; readOnly?: boolean }) {
 const [designation,setDesignation]=useState('Teacher Guardian Mentor (TGM)'),[employee,setEmployee]=useState(''),[preview,setPreview]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;void supabase.from('teachers').select('*').eq('user_id',userId).maybeSingle().then(async({data,error})=>{if(!active)return;if(error){setMessage('Teacher details unavailable');return;}if(data){setDesignation(data.designation);setEmployee(data.employee_id||'');if(data.photo_path){const r=await supabase.storage.from('faculty-photos').createSignedUrl(data.photo_path,300);if(active)setPreview(r.data?.signedUrl||'');}}});return()=>{active=false;};},[userId]);
 useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function save(){setBusy(true);setMessage('');try{let imagePath:null|string=null;if(file){const extension=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';imagePath=`${userId}/${crypto.randomUUID()}.${extension}`;const {error}=await supabase.storage.from('faculty-photos').upload(imagePath,file,{contentType:file.type,upsert:false});if(error)throw error;}const {error}=await supabase.rpc('save_teacher_details',{full_designation:designation,faculty_id:employee,image_path:imagePath});if(error)throw error;if(imagePath){const signed=await supabase.storage.from('faculty-photos').createSignedUrl(imagePath,300);setPreview(signed.data?.signedUrl||'');}setFile(null);setMessage('Teacher details saved.');}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Your previous photo is preserved.');}finally{setBusy(false);}}
 return <section className="rounded-xl border bg-white p-4 text-left text-slate-900"><h3 className="font-semibold">Faculty profile</h3>{preview&&<img src={preview} alt="Faculty profile" className="my-3 h-24 w-24 rounded object-cover"/>}{readOnly?<p className="text-sm">{designation}{employee&&` · Faculty ID: ${employee}`}</p>:<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void save();}}><label className="block text-sm">Designation<input required minLength={2} maxLength={120} className="block w-full rounded border p-2" value={designation} onChange={e=>setDesignation(e.target.value)}/></label><label className="block text-sm">Faculty ID (if assigned)<input maxLength={64} className="block w-full rounded border p-2" value={employee} onChange={e=>setEmployee(e.target.value)}/></label><label className="block text-sm">Profile photo (JPEG, PNG or WebP, up to 2 MB)<input type="file" accept="image/jpeg,image/png,image/webp" className="mt-1 block w-full" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>2097152){setMessage('Choose a JPEG, PNG or WebP image up to 2 MB.');return;}try{const bitmap=await createImageBitmap(f);bitmap.close();setFile(f);setMessage('');}catch{setMessage('This file could not be decoded as an image.');}}}/></label><button disabled={busy} className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">{busy?'Uploading / saving…':'Save faculty profile'}</button></form>}{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>;
}

